"""phase1 vote tables

Revision ID: 6482373e8ef1
Revises: 
Create Date: 2026-06-19 14:53:40.983879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6482373e8ef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('kakao_id', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_vote_match_id'), 'attendance_vote', ['match_id'], unique=False)
    op.create_table('featured',
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('title_id1', sa.String(length=50), nullable=True),
    sa.Column('title_id2', sa.String(length=50), nullable=True),
    sa.Column('title_id3', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('player_name')
    )
    op.create_table('mom_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('voter_name', sa.String(length=100), nullable=True),
    sa.Column('voted_for', sa.String(length=100), nullable=True),
    sa.Column('vote_type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mom_vote_match_id'), 'mom_vote', ['match_id'], unique=False)
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=True),
    sa.Column('auth', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('vote_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('kakao_id', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_comment_match_id'), 'vote_comment', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_comment_match_id'), table_name='vote_comment')
    op.drop_table('vote_comment')
    op.drop_table('push_subscription')
    op.drop_index(op.f('ix_mom_vote_match_id'), table_name='mom_vote')
    op.drop_table('mom_vote')
    op.drop_table('featured')
    op.drop_index(op.f('ix_attendance_vote_match_id'), table_name='attendance_vote')
    op.drop_table('attendance_vote')
    # ### end Alembic commands ###
