"""phase2 matches

Revision ID: ab8f77f9d8d5
Revises: 6482373e8ef1
Create Date: 2026-06-19 15:26:31.042810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8f77f9d8d5'
down_revision: Union[str, None] = '6482373e8ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('opponent', sa.String(length=200), nullable=True),
    sa.Column('our_score', sa.Integer(), nullable=True),
    sa.Column('their_score', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('assists', sa.Text(), nullable=True),
    sa.Column('mom', sa.String(length=100), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('attendance_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
