"""board tables + roster pref_pos

Revision ID: fec381e1209b
Revises: 4225bee24349
Create Date: 2026-07-24 09:52:18.810889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec381e1209b'
down_revision: Union[str, None] = '4225bee24349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('kakao_id', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_comment_post_id'), 'board_comment', ['post_id'], unique=False)
    op.create_table('board_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kakao_id', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('roster', sa.Column('pref_pos', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roster', 'pref_pos')
    op.drop_table('board_post')
    op.drop_index(op.f('ix_board_comment_post_id'), table_name='board_comment')
    op.drop_table('board_comment')
    # ### end Alembic commands ###
